version: '3.7'

services:
  web:
    build: .
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    volumes:
      - .:/web
      - /web/node_modules
